services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: on-failure
    volumes:
      - "${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql"
    env_file:
      - .env
    networks:
      - zoner_network

networks:
  zoner_network:
    name: zoner_network
